package com.magnusinfinity.magnusinfinitybackend.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

import java.util.Date;
import java.util.List;

@DynamoDBTable(tableName = "Candidate")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Candidate {

    @Id
    @DynamoDBHashKey
    private String emailId;

    @DynamoDBAttribute
    private String fullName;

    @DynamoDBAttribute
    private String mobileNumber;

    @DynamoDBAttribute
    private String location;

    @DynamoDBAttribute
    private String resumeUrl;

    @DynamoDBAttribute
    private Integer noticePeriod;

    @DynamoDBAttribute
    private String password; // put it encrypted

    @DynamoDBAttribute
    private String currentCompany;

    @DynamoDBAttribute
    private String currentTitle;

    @DynamoDBAttribute
    private Double currentCTC;

    @DynamoDBAttribute
    private Double expectedCTC;

    @DynamoDBAttribute
    private String linkedinUrl;

    @DynamoDBAttribute
    private Boolean isServingNoticePeriod;

    @DynamoDBAttribute
    private Date noticePeriodStartDate;

    @DynamoDBAttribute
    private Float experience;

    @DynamoDBAttribute
    private List<String> skills;

    @DynamoDBAttribute
    private Date createdAt;

    @DynamoDBAttribute
    private Date updatedAt;


}
