package com.magnusinfinity.magnusinfinitybackend.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.magnusinfinity.magnusinfinitybackend.model.AuthProvider;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "User")
@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class User {
    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(attributeName = "email", globalSecondaryIndexName = "email")
    private String email;

    @DynamoDBAttribute
    private String imageUrl;

    @DynamoDBAttribute
    private Boolean emailVerified = false;

    @DynamoDBAttribute
    private String password;

    @DynamoDBTypeConvertedEnum
    private AuthProvider provider;

    private String providerId;

    @DynamoDBAttribute
    private String role;
}
